AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 130

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Naming/FileName:
 Exclude:
   - lib/rubocop-isucon.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes
