AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  Exclude:
    - 'gemfiles/vendor/**/*'
    - 'benchmark/**/*'

    # https://github.com/rubocop/rubocop/blob/v1.20.0/config/default.yml
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Max: 130

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Naming/FileName:
 Exclude:
   - lib/rubocop-isucon.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
