# Isucon/Mysql2:
#   Database:
#     adapter: mysql2
#     host: # TODO: Fix this
#     database: # TODO: Fix this
#     username: isucon
#     password: isucon
#     encoding: utf8
#     port: 3306

Isucon/Mysql2/JoinWithoutIndex:
  Description: 'Check for `JOIN` without index'
  Enabled: true
  VersionAdded: '<<next>>'
  # Database:
  #   adapter: mysql2
  #   host: # TODO: Fix this
  #   database: # TODO: Fix this
  #   username: isucon
  #   password: isucon
  #   encoding: utf8
  #   port: 3306

Isucon/Mysql2/NPlusOneQuery:
  Description: 'Checks that N+1 query is not used'
  Enabled: true
  VersionAdded: '<<next>>'

Isucon/Mysql2/SelectAsterisk:
  Description: 'Avoid `SELECT *` in `db.xquery`'
  Enabled: true
  VersionAdded: '<<next>>'
  # Database:
  #   adapter: mysql2
  #   host: # TODO: Fix this
  #   database: # TODO: Fix this
  #   username: isucon
  #   password: isucon
  #   encoding: utf8
  #   port: 3306

Isucon/Mysql2/WhereWithoutIndex:
  Description: 'Check for `WHERE` without index'
  Enabled: true
  VersionAdded: '<<next>>'
  # Database:
  #   adapter: mysql2
  #   host: # TODO: Fix this
  #   database: # TODO: Fix this
  #   username: isucon
  #   password: isucon
  #   encoding: utf8
  #   port: 3306

Isucon/Sinatra/DisableLogging:
  Description: 'Disable sinatra logging'
  Enabled: true
  VersionAdded: '<<next>>'
