Isucon/Mysql2:
  StyleGuideBaseURL: https://sue445.github.io/rubocop-isucon/RuboCop/Cop/Isucon/Mysql2/
  # Database:
  #   adapter: mysql2
  #   host: # TODO: Fix this
  #   database: # TODO: Fix this
  #   username: isucon
  #   password: isucon
  #   encoding: utf8
  #   port: 3306

Isucon/Mysql2/JoinWithoutIndex:
  Description: 'Check for `JOIN` without index'
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: JoinWithoutIndex.html
  # Database:
  #   adapter: mysql2
  #   host: # TODO: Fix this
  #   database: # TODO: Fix this
  #   username: isucon
  #   password: isucon
  #   encoding: utf8
  #   port: 3306

Isucon/Mysql2/NPlusOneQuery:
  Description: 'Checks that N+1 query is not used'
  Enabled: true
  VersionAdded: '0.1.0'
  SafeAutoCorrect: false
  StyleGuide: NPlusOneQuery.html
  # Database:
  #   adapter: mysql2
  #   host: # TODO: Fix this
  #   database: # TODO: Fix this
  #   username: isucon
  #   password: isucon
  #   encoding: utf8
  #   port: 3306

Isucon/Mysql2/SelectAsterisk:
  Description: 'Avoid `SELECT *` in `db.xquery`'
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: SelectAsterisk.html
  # Database:
  #   adapter: mysql2
  #   host: # TODO: Fix this
  #   database: # TODO: Fix this
  #   username: isucon
  #   password: isucon
  #   encoding: utf8
  #   port: 3306

Isucon/Mysql2/WhereWithoutIndex:
  Description: 'Check for `WHERE` without index'
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: WhereWithoutIndex.html
  # Database:
  #   adapter: mysql2
  #   host: # TODO: Fix this
  #   database: # TODO: Fix this
  #   username: isucon
  #   password: isucon
  #   encoding: utf8
  #   port: 3306

Isucon/Shell/Backtick:
  Description: 'TODO: Write a description of the cop.'
  Enabled: pending
  VersionAdded: '<<next>>'

Isucon/Sinatra:
  StyleGuideBaseURL: https://sue445.github.io/rubocop-isucon/RuboCop/Cop/Isucon/Sinatra/

Isucon/Sinatra/DisableLogging:
  Description: 'Disable sinatra logging'
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: DisableLogging.html

Isucon/Sinatra/RackLogger:
  Description: "Don't use `request.env['rack.logger']`"
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: RackLogger.html

Isucon/Sinatra/ServeStaticFile:
  Description: 'Serve static files on front server (e.g. nginx) instead of sinatra app'
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: ServeStaticFile.html
