Isucon/Mysql2:
  StyleGuideBaseURL: https://sue445.github.io/rubocop-isucon/RuboCop/Cop/Isucon/Mysql2/
  Database:

Isucon/Mysql2/JoinWithoutIndex:
  Description: 'Check for `JOIN` without index'
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: JoinWithoutIndex.html

Isucon/Mysql2/ManyJoinTable:
  Description: 'Check if SQL contains many JOINs'
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: ManyJoinTable.html
  CountTables: 3

Isucon/Mysql2/NPlusOneQuery:
  Description: 'Checks that N+1 query is not used'
  Enabled: true
  VersionAdded: '0.1.0'
  SafeAutoCorrect: false
  StyleGuide: NPlusOneQuery.html

Isucon/Mysql2/PrepareExecute:
  Description: 'Use `db.xquery` instead of `db.prepare`'
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: PrepareExecute.html

Isucon/Mysql2/SelectAsterisk:
  Description: 'Avoid `SELECT *` in `db.xquery`'
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: SelectAsterisk.html

Isucon/Mysql2/WhereWithoutIndex:
  Description: 'Check for `WHERE` without index'
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: WhereWithoutIndex.html

Isucon/Shell:
  StyleGuideBaseURL: https://sue445.github.io/rubocop-isucon/RuboCop/Cop/Isucon/Shell/

Isucon/Shell/Backtick:
  Description: 'Avoid external command calls with backtick'
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: Backtick.html

Isucon/Shell/System:
  Description: 'Avoid external command calls with `Kernel#system`'
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: System.html

Isucon/Sinatra:
  StyleGuideBaseURL: https://sue445.github.io/rubocop-isucon/RuboCop/Cop/Isucon/Sinatra/

Isucon/Sinatra/DisableLogging:
  Description: 'Disable sinatra logging'
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: DisableLogging.html

Isucon/Sinatra/Logger:
  Description: "Disable sinatra logger logging"
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: Logger.html

Isucon/Sinatra/RackLogger:
  Description: "Disable `request.env['rack.logger']` logging"
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: RackLogger.html

Isucon/Sinatra/ServeStaticFile:
  Description: 'Serve static files on front server (e.g. nginx) instead of sinatra app'
  Enabled: true
  VersionAdded: '0.1.0'
  StyleGuide: ServeStaticFile.html

Isucon/Sqlite3:
  StyleGuideBaseURL: https://sue445.github.io/rubocop-isucon/RuboCop/Cop/Isucon/Sqlite3/
  Database:

Isucon/Sqlite3/JoinWithoutIndex:
  Description: 'Check for `JOIN` without index'
  Enabled: true
  VersionAdded: '0.2.0'
  StyleGuide: JoinWithoutIndex.html

Isucon/Sqlite3/SelectAsterisk:
  Description: 'Avoid `SELECT *` in `db.execute`'
  Enabled: true
  VersionAdded: '0.2.0'
  StyleGuide: SelectAsterisk.html

Isucon/Sqlite3/WhereWithoutIndex:
  Description: 'Check for `WHERE` without index'
  Enabled: true
  VersionAdded: '0.2.0'
  StyleGuide: WhereWithoutIndex.html
