name: Publish gem to rubygems.org

on:
  workflow_dispatch:

jobs:
  release:
    uses: sue445/workflows/.github/workflows/release_gem.yml@main
    with:
      repo-name: sue445/rubocop-isucon
      gem-name:  rubocop-isucon
      before-command: |
        set -xe
        sudo apt-get update
        sudo apt-get install -y libgda-5.0
    permissions:
      contents: write
      id-token: write
